//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Wave_Recorder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public uint SettingBufferSize {
            get {
                return ((uint)(this["SettingBufferSize"]));
            }
            set {
                this["SettingBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public uint SettingBufferCount {
            get {
                return ((uint)(this["SettingBufferCount"]));
            }
            set {
                this["SettingBufferCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingOutputPath {
            get {
                return ((string)(this["SettingOutputPath"]));
            }
            set {
                this["SettingOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16384")]
        public int SettingAmplitudeThreshold {
            get {
                return ((int)(this["SettingAmplitudeThreshold"]));
            }
            set {
                this["SettingAmplitudeThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48000")]
        public int SettingSamplesPerSecond {
            get {
                return ((int)(this["SettingSamplesPerSecond"]));
            }
            set {
                this["SettingSamplesPerSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public ushort SettingBitsPerSample {
            get {
                return ((ushort)(this["SettingBitsPerSample"]));
            }
            set {
                this["SettingBitsPerSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte SettingChannels {
            get {
                return ((byte)(this["SettingChannels"]));
            }
            set {
                this["SettingChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SettingAudioInputDevice {
            get {
                return ((int)(this["SettingAudioInputDevice"]));
            }
            set {
                this["SettingAudioInputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SettingAudioOutputDevice {
            get {
                return ((int)(this["SettingAudioOutputDevice"]));
            }
            set {
                this["SettingAudioOutputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingLoopPlayback {
            get {
                return ((bool)(this["SettingLoopPlayback"]));
            }
            set {
                this["SettingLoopPlayback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingGraphClicked {
            get {
                return ((bool)(this["SettingGraphClicked"]));
            }
            set {
                this["SettingGraphClicked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq100 {
            get {
                return ((int)(this["SettingLeftEq100"]));
            }
            set {
                this["SettingLeftEq100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq200 {
            get {
                return ((int)(this["SettingLeftEq200"]));
            }
            set {
                this["SettingLeftEq200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq400 {
            get {
                return ((int)(this["SettingLeftEq400"]));
            }
            set {
                this["SettingLeftEq400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq800 {
            get {
                return ((int)(this["SettingLeftEq800"]));
            }
            set {
                this["SettingLeftEq800"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq1600 {
            get {
                return ((int)(this["SettingLeftEq1600"]));
            }
            set {
                this["SettingLeftEq1600"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq3200 {
            get {
                return ((int)(this["SettingLeftEq3200"]));
            }
            set {
                this["SettingLeftEq3200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingLeftEq6400 {
            get {
                return ((int)(this["SettingLeftEq6400"]));
            }
            set {
                this["SettingLeftEq6400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq100 {
            get {
                return ((int)(this["SettingRightEq100"]));
            }
            set {
                this["SettingRightEq100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq200 {
            get {
                return ((int)(this["SettingRightEq200"]));
            }
            set {
                this["SettingRightEq200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq400 {
            get {
                return ((int)(this["SettingRightEq400"]));
            }
            set {
                this["SettingRightEq400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq800 {
            get {
                return ((int)(this["SettingRightEq800"]));
            }
            set {
                this["SettingRightEq800"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq1600 {
            get {
                return ((int)(this["SettingRightEq1600"]));
            }
            set {
                this["SettingRightEq1600"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq3200 {
            get {
                return ((int)(this["SettingRightEq3200"]));
            }
            set {
                this["SettingRightEq3200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingRightEq6400 {
            get {
                return ((int)(this["SettingRightEq6400"]));
            }
            set {
                this["SettingRightEq6400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingEqOn {
            get {
                return ((bool)(this["SettingEqOn"]));
            }
            set {
                this["SettingEqOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingLowPassOn {
            get {
                return ((bool)(this["SettingLowPassOn"]));
            }
            set {
                this["SettingLowPassOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingHighPassOn {
            get {
                return ((bool)(this["SettingHighPassOn"]));
            }
            set {
                this["SettingHighPassOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingEqShowing {
            get {
                return ((bool)(this["SettingEqShowing"]));
            }
            set {
                this["SettingEqShowing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingRepeatOn {
            get {
                return ((bool)(this["SettingRepeatOn"]));
            }
            set {
                this["SettingRepeatOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public int SettingVolume {
            get {
                return ((int)(this["SettingVolume"]));
            }
            set {
                this["SettingVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingInputPath {
            get {
                return ((string)(this["SettingInputPath"]));
            }
            set {
                this["SettingInputPath"] = value;
            }
        }
    }
}
